DatabaseConsistencySettings:
  color: true

Athlete:
  index_athletes_on_user_id:
    UniqueIndexChecker:
      enabled: false
  male:
    ThreeStateBooleanChecker:
      enabled: false

Permission:
  event:
    ForeignKeyChecker:
      enabled: false

User:
  index_users_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false
  index_users_on_confirmation_token:
    UniqueIndexChecker:
      enabled: false
  index_users_on_unlock_token:
    UniqueIndexChecker:
      enabled: false
